ALTER TABLE dbo.NHANVIEN ADD chisoluong FLOAT 
DECLARE @cur CURSOR
SET @cur = CURSOR FOR SELECT NgBD,NgKT,MaNV FROM dbo.HOPDONG
DECLARE @ngbd DATE
DECLARE @ngkt DATE
DECLARE @mnv VARCHAR(10)
OPEN @cur
FETCH NEXT FROM @cur INTO @ngbd,@ngkt,@mnv
WHILE @@FETCH_STATUS=0
BEGIN
UPDATE dbo.NHANVIEN SET chisoluong= 1.2 WHERE DATEDIFF(YEAR,@ngbd,GETDATE()) < 3 AND @ngkt>GETDATE() AND @mnv=MaNV
UPDATE dbo.NHANVIEN SET chisoluong= 1.8 WHERE (DATEDIFF(YEAR,@ngbd,GETDATE()) BETWEEN 3 AND 5)  AND @ngkt>GETDATE() AND @mnv=MaNV
UPDATE dbo.NHANVIEN SET chisoluong= 2.0 WHERE DATEDIFF(YEAR,@ngbd,GETDATE()) > 5 AND @ngkt>GETDATE() AND @mnv=MaNV
FETCH NEXT FROM @cur INTO @ngbd,@ngkt,@mnv
END
CLOSE @cur
DEALLOCATE @cur

